data <- read.csv('household_power_consumption.txt', sep=';')
data[,1] <- as.Date(data[,1],'%d/%m/%Y')
ld = as.Date('2007-02-01','%Y-%m-%d')
rd = as.Date('2007-02-02','%Y-%m-%d')
df = data[data[,1]>=ld & data[,1]<=rd,]
df[,7] <- as.numeric(df[,7])
df[,8] <- as.numeric(df[,8])
df[,9] <- as.numeric(df[,9])
x <- strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S")
plot(x, df$Sub_metering_1, xlab='', ylab='Energy sub metering', type="n")
lines(x, df$Sub_metering_1, col='gray')
lines(x, df$Sub_metering_2, col='red')
lines(x, df$Sub_metering_3, col='blue')
legend("topright", col = c("gray","red", "blue"), lty=c(1,1), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
